const dictionary = [
["makean veden kala",	"freshwater fish"],
["suolaisen veden kala",	"salt water fish"],
["ahven",	"perch"],
["ankerias",	"eel"],
["delfiini",	"dolphin"],
["harjus",	"greyling"],
["harmaanieriä",	"lake trout"],
["hauki",	"pike"],
["kampela",	"flounder"],
["kapakala",	"dried cod"],
["karppi",	"carp"],
["kiiski",	"ruffe"],
["kirjolohi",	"rainbow trout"],
["kolja",	"haddock"],
["kuha",	"pikeperch"],
["kuore",	"smelt"],
["lahna",	"bream"],
["lohi",	"salmon"],
["makrilli",	"mackerel"],
["meriahven",	"sea bass"],
["meriantura",	"sole"],
["merilohi",	"Atlantic salmon"],
["meritaimen",	"sea trout"],
["miekkakala",	"swordfish"],
["miekkavalas",	"killer whale"],
["miljoonakala",	"guppy"],
["muikku",	"vendace"],
["mullo",	"mullet"],
["nahkiainen",	"lamprey"],
["nieriä",	"char"],
["pallas",	"halibut"],
["pallokala",	"pufferfish"],
["piikkikampela","turbot"],
["piraija",	"piranha"],
["puna-ahven",	"red snapper"],
["punakampela",	"plaice"],
["puronieriä",	"brook trout"],
["rausku",	"manta ray"],
["ruutana",	"sturgeon"],
["ryhävalas",	"humpback whale"],
["sardelli",	"anchovy"],
["seepia",	"cuttlefish"],
["seiti",	"haddock"],
["siika","lake whitefish"],
["silakka",	"Baltic herring"],
["silli",	"herring"],
["sinivalas",	"blue whale"],
["suutari",	"tench"],
["särki",	"roach"],
["säyne	ide", "chub"]
]

console.log(dictionary[49][1])